// constants/navigation.js
const ItensNavigation = [
  {
    id: 'home',
    label: 'Home',
    icon: 'ak ak-home',
    to: '/app/home',
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1, 2],
  },
  {
    id: 'processos',
    label: 'Processos',
    icon: 'ak ak-processo',
    to: '/app/processo',
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1, 2],
  },
  {
    id: 'bases',
    label: "Minhas Bases",
    icon: "ak ak-database",
    to: "/app/base",
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1, 2],
  },
  {
    id: 'atividades',
    label: 'Atividades',
    icon: 'ak ak-tarefas',
    to: '/app/quadro',
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1, 2],
  },
  {
    id: 'insights',
    label: 'Meus Insights',
    icon: 'ak ak-lightbulb-fill',
    to: '/app/chart',
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1, 2],
  },

  {
    id: 'chat',
    label: 'Chat',
    icon: 'ak ak-chats-fill',
    to: '/app/chat',
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1, 2],
  },
  {
    id: 'admin',
    label: 'Administração',
    icon: 'ak ak-gear-six',
    template: 'Item_Topico',
    accessLevelAllowed: [0, 1],
    items: [
      {
        id: 'admin-processo',
        label: 'Processo',
        icon: 'ak ak-gear-six',
        template: 'Item_Topico',
        accessLevelAllowed: [0, 1],
        items: [
          {
            id: 'admin-advogado',
            to: '/app/adm/advogado',
            label: 'Advogado',
            icon: 'pi pi-bars',
            template: 'Item_Renderer',
            accessLevelAllowed: [0, 1],
          },
          {
            id: 'admin-escritorio',
            to: '/app/adm/escritorio-advogado',
            label: 'Escritorios de advogado',
            icon: 'pi pi-bars',
            template: 'Item_Renderer',
            accessLevelAllowed: [0, 1],
          },
          {
            id: 'admin-reclamante',
            to: '/app/adm/reclamante',
            label: 'Reclamante',
            icon: 'pi pi-bars',
            template: 'Item_Renderer',
            accessLevelAllowed: [0, 1],
          },
          {
            id: 'admin-preposto',
            to: '/app/adm/preposto',
            label: 'Preposto',
            icon: 'pi pi-bars',
            template: 'Item_Renderer',
            accessLevelAllowed: [0, 1],
          },
          {
            id: 'admin-testemunha',
            to: '/app/adm/testemunha',
            label: 'Testemunha',
            icon: 'pi pi-bars',
            template: 'Item_Renderer',
            accessLevelAllowed: [0, 1],
          }
        ]
      },
      {
        id: 'admin-usuario',
        to: '/app/adm/usuario',
        label: 'Usuario',
        icon: 'pi pi-bars',
        template: 'Item_Renderer',
        accessLevelAllowed: [0, 1],
      },
      {
        id: 'admin-acesso-rapido',
        to: '/app/adm/possivel-link-acesso-rapido',
        label: 'Acesso Rapido',
        icon: 'pi pi-bars',
        template: 'Item_Renderer',
        accessLevelAllowed: [0, 1],
      },
      {
        id: 'admin-planos',
        to: '/app/adm-ak/planos',
        label: 'Planos',
        icon: 'pi pi-bars',
        template: 'Item_Renderer',
        accessLevelAllowed: [0],
      },
      {
        id: 'admin-config',
        to: '/app/adm-ak/configuracoes-sistema',
        label: 'Configuracoes do Sistema',
        icon: 'pi pi-bars',
        template: 'Item_Renderer',
        accessLevelAllowed: [0],
      },
      {
        id: 'admin-ai',
        to: '/app/adm-ak/inteligencia-artificial',
        label: 'Lista AI',
        icon: 'pi pi-bars',
        template: 'Item_Renderer',
        accessLevelAllowed: [0],
      },
      {
        id: 'admin-empresas',
        to: '/app/adm-ak/empresa',
        label: 'Lista Empresas',
        icon: 'pi pi-bars',
        template: 'Item_Renderer',
        accessLevelAllowed: [0],
      },
    ],
  },
];

export default ItensNavigation;