const UrlAndNamePages = [
  { url: "/app/", name: "Bem-vindo" },
  { url: "/app/home", name: "Home" },
  { url: "/app/notifications", name: "Notifications" },
  { url: "/app/adm/usuario", name: "Todos os usuarios" },
  { url: "/app/adm/usuario/new", name: "Novo Usuarios" },
  { url: "/app/adm/usuario/update", name: "Atualizar Usuario" },
  { url: "/app/adm/possivel-link-acesso-rapido", name: "Gestão Acesso Rapido" },
  { url: "/app/adm/escritorio-advogado", name: "Todos escritorios de advogado" },
  { url: "/app/adm/advogado", name: "Todos os advogado" },
  { url: "/app/adm/preposto", name: "Todos os preposto" },
  { url: "/app/adm/testemunha", name: "Todos os testemunhas" },
  { url: "/app/adm/reclamante", name: "Todos os reclamantes" },
  { url: "/app/adm-ak/controle-clientes", name: "Controle de Clientes" },
  { url: "/app/adm-ak/planos", name: "Planos" },
  { url: "/app/adm-ak/configuracoes-sistema", name: "Configuracoes de Sistema" },
  { url: "/app/adm-ak/inteligencia-artificial", name: "Lista de Inteligências Artificiais" },
  { url: "/app/adm-ak/inteligencia-artificial/nova", name: "Nova Inteligências Artificiais" },
  { url: "/app/adm-ak/empresa", name: "Lista Empresas" },
  { url: "/app/adm-ak/empresa/edit", name: "Atulizar empresa" },
  { url: "/app/adm-ak/empresa/new", name: "Nova empresa" },
  { url: "/app/quadro", name: "Quadro" },
  { url: "/app/quadro/visao-detalhes", name: "Quadro" },
  { url: "/app/quadro/visao-calendarios", name: "Quadro" },
  { url: "/app/quadro/visao-lista", name: "Quadro" },
  { url: "/app/chat", name: "Chats" },
  { url: "/app/chart", name: "Chart" },
  { url: "/app/enriquecimento", name: "Enriquecimento" },
  { url: "/app/sua-conta", name: "Sua Conta" },
  { url: "/app/base", name: "Minhas Bases" },
  { url: "/app/minha-bases/cadastro", name: "Nova Bases" },
  { url: "/app/minha-bases/continuar-cadastro", name: "Atualizar Base" },
  { url: "/app/acesso-rapido", name: "Acesso rapido" },
  { url: "/app/ia", name: "Motores (IA)" },
  { url: "/app/ia/chat", name: "Motores (IA)" },
  { url: "/app/processo", name: "Todos os processos" },
  { url: "/app/processo/novo", name: "Novo processo" },
];

export default UrlAndNamePages;